spring:
  datasource:
#annouce数据库
    annouce:
      url: jdbc:mysql://localhost:3306/annouce
      username: test
      password: root123
#user数据库
    user: 
      url: jdbc:mysql://localhost:3306/user
      username: test
      password: root123
    tomcat:
      max-active: 0
      max-idle: 0
      min-idle: 0
      max-wait: -1
      initial-size: 10      
#sql日志打印
  jpa:
    show-sql: true
    properties: 
      hibernate: 
        format_sql: false
#session类型-redis
  session:
    store-type: redis
  redis:
    timeout: 6000
    host: 127.0.0.1
    port: 6379
    password: 
    database: 0
    jedis:
#连接超时
      pool: 
#最大连接数
        max-active: 8
#异常抛出之前的等待时间 ms
        max-wait: -1
#最大空闲数
        max-idle: 5          
#最小空闲数
        min-idle: 0
#日志级别
logging: 
  level:
    root: info
    org :
      hibernate: info 
      springframework: 
        web: info
#session 有效时间
server:
  servlet:
    session:
      timeout: 600

#自定义      
schedul:
    pool:
      size:
        core: 10
        max: 200
    queue:
      capacity: 5
sql:
  batch:
    size: 50
  query:
    page:
      size: 10