
alter table announcement_collector_result rename to annouce_collector_result;

CREATE TABLE ANNOUCE_WEBSITE_INFO
(
	AWI_FLOW_NO VARCHAR(50) PRIMARY KEY COMMENT '流水号，主键',
	AWI_WEBSITE_URL VARCHAR(50) COMMENT '网站url',
	AWI_WEBSITE_CODE VARCHAR(10) COMMENT '网站代码',
	AWI_WEBSITE_NAME VARCHAR(100) COMMENT '网站名称',
	AWI_TITLE_REGEX VARCHAR(50) COMMENT '搜索标题的正则表达式',
	AWI_STATE CHAR(1) COMMENT '状态',
	AWI_CREATE_TIME VARCHAR(14) COMMENT '创建时间',
	AWI_CREATE_USERNAME VARCHAR(30) COMMENT '创建人',
	AWI_MODIFY_TIME VARCHAR(14) COMMENT '修改时间',
	AWI_MODIFY_USERNAME VARCHAR(30) COMMENT '修改人'
)COMMENT='网站信息表';

CREATE TABLE ANNOUCE_COLLECTOR_INFO
(
	ACI_FLOW_NO VARCHAR(50) PRIMARY KEY COMMENT '流水号，主键',
	ACI_AWI_FLOW_NO VARCHAR(50) COMMENT 'AWI表的流水号',
	ACI_TITLE_URL_REGEX_WHITE VARCHAR(100) COMMENT '标题url正则表达式-白名单',
	ACI_CATEGORY_CODE VARCHAR(10) COMMENT '内容分类-代码',
	ACI_CATEGORY_NAME VARCHAR(100) COMMENT '内容分类-名称',
	ACI_TEXT_URL_REGEX_WHITE VARCHAR(100) COMMENT '正文url正则表达式-白名单',
	ACI_TEXT_URL_REGEX_BLACK VARCHAR(100) COMMENT '正文url正则表达式-黑名单',
	ACI_STATE CHAR(1) COMMENT '状态',
	ACI_CREATE_TIME VARCHAR(14) COMMENT '创建时间',
	ACI_CREATE_USERNAME VARCHAR(30) COMMENT '创建人',
	ACI_MODIFY_TIME VARCHAR(14) COMMENT '修改时间',
	ACI_MODIFY_USERNAME VARCHAR(30)	COMMENT '修改人'
)COMMENT='搜索器信息表';