create table uc_user_info
(
	UUI_PHONE_NO CHAR(11) PRIMARY KEY COMMENT '手机号，主键',
	UUI_NAME VARCHAR(30) NOT NULL COMMENT '名',
	UUI_GENDER CHAR(1) NOT NULL DEFAULT '9' COMMENT '性别，0-男，1-女，9-未知',
	UUI_IDENTIFICATION_TYPE CHAR(2) DEFAULT '00' COMMENT '证件类型，00-身份证',
	UUI_IDENTIFICATION_NO VARCHAR(18) COMMENT '证件号',
	UUI_NATIVE_ADDRESS VARCHAR(50) COMMENT '籍贯',
	UUI_CURRENT_ADDRESS VARCHAR(50) COMMENT '现住址',
	UUI_PASSWORD VARCHAR(50) COMMENT '密码',
	UUI_OPENID VARCHAR(20) COMMENT '微信openid',
	UUI_STATE CHAR(1) NOT NULL DEFAULT '0' COMMENT '状态，0-可用，1-删除，2-冻结'
)COMMENT='用户表';
